name = "tour-api-proxy"
main = "tour-api-proxy.js"
compatibility_date = "2025-09-08"

# Environment variables
[vars]
# This will be set in the Cloudflare dashboard
# TOUR_API_KEY = "YourApiKey"

# Route configuration (update with your domain)
# Uncomment and update these lines after deployment
# [[routes]]
# pattern = "api.tour.yourdomain.com/api/tour/*"
# script_name = "tour-api-proxy"
# zone_name = "yourdomain.com"
